name: sigrok-suite
version: '2019-07-29-2-master'
summary: sigrok suite (sigrok-cli and pulseview)
description: |
  The sigrok project aims at creating a portable, cross-platform, Free/Libre/Open-Source
  signal analysis software suite that supports various device types
  (e.g. logic analyzers, oscilloscopes, and many more).

grade: stable
# confinement: classic
icon: sigrok_logo.png

# https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
plugs:
  gnome-3-28-1804:
    interface: content
    target: gnome-platform
    default-provider: gnome-3-28-1804

# environment:
#   PATH: $SNAP/bin:$SNAP/usr/bin

apps:
  sigrok-cli:
    command: sigrok-cli
    plugs:
      - home
      - network
      - raw-usb
      - serial-port
      - bluez
  pulseview:
    command: desktop-launch pulseview
    plugs:
      - home
      - network
      - raw-usb
      - serial-port
      - bluez
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - opengl
      - gsettings
      - gnome-3-28-1804

  # sigrok-meter:
  #   command: bin/desktop-launch bin/sigrok-meter
  #   plugs:
  #     - home
  #     - network
  #     - raw-usb
  #     - serial-port
  #     - desktop
  #     - desktop-legacy
  #     - wayland
  #     - unity7
  #     - opengl
  #     - gsettings
  #     - gnome-3-28-1804

parts:
  libserialport:
    source: git://sigrok.org/libserialport
    plugin: autotools
  libsigrokdecode:
    source: git://sigrok.org/libsigrokdecode
    plugin: autotools
    stage-packages:
      - libglib2.0-0
      - libdb5.3
      - libpython3.5
    build-packages:
      - libglib2.0-dev
      - python3-dev
    override-build: |
      export PYTHON=/usr/bin/python3
      env NOCONFIGURE=1 ./autogen.sh
      ./configure --prefix=
      make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT
      make DESTDIR=$SNAPCRAFT_PART_INSTALL install
  libsigrok:
    source: git://sigrok.org/libsigrok
    plugin: autotools
    after:
      - libserialport
    build-packages:
      - g++
      - libglib2.0-dev
      - libglibmm-2.4-dev
      - libzip-dev
      - libusb-1.0-0-dev
      - libftdi1-dev
      - libieee1284-3-dev
      - check
      - python3-numpy
      - python3-dev
      - python3-gi
      - python-gi-dev
      - python3-setuptools
      - swig
      - doxygen
    stage-packages:
      - libglib2.0-0
      - libglibmm-2.4-1v5
      - libzip4
      - libusb-1.0-0
      - libftdi1-2
      - libieee1284-3
      - libpython3.5
    override-build: |
      export PYTHON=/usr/bin/python3
      env NOCONFIGURE=1 ./autogen.sh
      ./configure --prefix=
      make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT
      make DESTDIR=$SNAPCRAFT_PART_INSTALL install
  sigrok-firmware-fx2lafw:
    source: git://sigrok.org/sigrok-firmware-fx2lafw
    plugin: autotools
    build-packages:
      - sdcc
  sigrok-util:
    source: git://sigrok.org/sigrok-util
    plugin: dump
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      PREFIX="$SNAPCRAFT_PART_INSTALL" firmware/dreamsourcelab-dslogic/sigrok-fwextract-dreamsourcelab-dslogic
      pip3 install pyserial bluepy
      install -t $SNAPCRAFT_PART_INSTALL/bin util/eevblog-121gw/eev121gw-ble-uart-relay
    prime:
      - share/sigrok-firmware/*.fw
    build-packages:
      - python3-wheel
      - python3-pip
      - wget
  sigrok-cli:
    source: git://sigrok.org/sigrok-cli
    plugin: autotools
    after:
      - libsigrok
      - libsigrokdecode
      - sigrok-firmware-fx2lafw
      - sigrok-util
    build-packages:
      - libglib2.0-dev
  pulseview:
    source: git://sigrok.org/pulseview
    plugin: cmake
    after:
      - desktop-qt5
      - libsigrok
      - libsigrokdecode
      - sigrok-firmware-fx2lafw
      - sigrok-util
    build-packages:
      - libglib2.0-dev
      - libboost-test-dev
      - libboost-thread-dev
      - libboost-filesystem-dev
      - libboost-system-dev
      - libqt5opengl5-dev
      - libqt5svg5-dev
      - qtbase5-dev
    stage-packages:
      - libboost-serialization1.58.0
  # sigrok-meter:
  #   source: git://sigrok.org/sigrok-meter
  #   plugin: make
  #   after:
  #     - desktop-qt5
  #     - libsigrok
  #     - libsigrokdecode
  #     - sigrok-firmware-fx2lafw
  #     - sigrok-util
  #   stage-packages:
  #     - python-pyqtgraph
  #   build-packages:
  #     - pyqt4-dev-tools
  #     - qtbase5-dev
