name: sigrok-suite
version: '20180820-master'
summary: sigrok suite (sigrok-cli and pulseview)
description: |
  The sigrok project aims at creating a portable, cross-platform, Free/Libre/Open-Source
  signal analysis software suite that supports various device types
  (e.g. logic analyzers, oscilloscopes, and many more).

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
icon: sigrok_logo.png

plugs:
  ubuntu-app-platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform
  gnome-3-28-1804:
    interface: content
    content: gnome-3-28-1804
    default-provider: gnome-3-28-1804
    target: gnome-platform

apps:
  sigrok-cli:
    command: sigrok-cli
    desktop: share/applications/org.sigrok.sigrok-cli.desktop
    plugs:
      - home
      - network
      - raw-usb
      - serial-port
  pulseview:
    command: desktop-launch pulseview
    desktop: share/applications/org.sigrok.PulseView.desktop
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - network
      - opengl
      - gsettings
      - raw-usb
      - serial-port
      - ubuntu-app-platform
  # sigrok-meter:
  #   command: desktop-launch sigrok-meter
  #   plugs:
  #     - desktop
  #     - desktop-legacy
  #     - wayland
  #     - unity7
  #     - home
  #     - network
  #     - opengl
  #     - gsettings
  #     - raw-usb
  #     - serial-port
  #     - ubuntu-app-platform

parts:
  libserialport:
    source: git://sigrok.org/libserialport
    plugin: autotools
  libsigrokdecode:
    source: git://sigrok.org/libsigrokdecode
    plugin: autotools
    stage-packages:
      - libglib2.0-0
      - python3
    build-packages:
      - libglib2.0-dev
      - python3-dev
  libsigrok:
    source: git://sigrok.org/libsigrok
    plugin: autotools
    after:
      - libserialport
    stage-packages:
      - libglib2.0-0
      - libglibmm-2.4-1v5
      - libzip4
      - libusb-1.0-0
      - libftdi1
      - libieee1284-3
    build-packages:
      - g++
      - libglib2.0-dev
      - libglibmm-2.4-dev
      - libzip-dev
      - libusb-1.0-0-dev
      - libftdi1-dev
      - libieee1284-3-dev
      - check
      - python-numpy
      - python-dev
      - python-gi-dev
      - python-setuptools
      - swig
      - doxygen
  sigrok-firmware-fx2lafw:
    source: git://sigrok.org/sigrok-firmware-fx2lafw
    plugin: autotools
    build-packages:
      - sdcc
  sigrok-util:
    source: git://sigrok.org/sigrok-util
    plugin: dump
    override-build: |
      PREFIX="$SNAPCRAFT_STAGE" firmware/dreamsourcelab-dslogic/sigrok-fwextract-dreamsourcelab-dslogic
    prime:
      - share/sigrok-firmware/*.fw
    build-packages:
      - wget
  sigrok-cli:
    source: git://sigrok.org/sigrok-cli
    plugin: autotools
    after:
      - libsigrok
      - libsigrokdecode
      - sigrok-firmware-fx2lafw
      - sigrok-util
    build-packages:
      - libglib2.0-dev
  pulseview:
    source: git://sigrok.org/pulseview
    plugin: cmake
    after:
      - desktop-qt5
      - libsigrok
      - libsigrokdecode
      - sigrok-firmware-fx2lafw
      - sigrok-util
    build-packages:
      - libglib2.0-dev
      - libboost-test-dev
      - libboost-thread-dev
      - libboost-filesystem-dev
      - libboost-system-dev
      - libqt5opengl5-dev
      - libqt5svg5-dev
      - qtbase5-dev
  # sigrok-meter:
  #   source: git://sigrok.org/sigrok-meter
  #   plugin: make
  #   after:
  #     - desktop-qt5
  #     - libsigrok
  #     - libsigrokdecode
  #     - sigrok-firmware-fx2lafw
  #     - sigrok-util
  #   stage-packages:
  #     - python-pyqtgraph
  #   build-packages:
  #     - pyqt4-dev-tools
  #     - qtbase5-dev
